import SearchBar from "components/SearchBar"
import useLoading from "hooks/useLoading"
import Head from "next/head"
import { ReactNode } from "react"
import styles from "./styles.module.scss"

interface Iprops {
  children: ReactNode
}

export default function Layout({ children }: Iprops) {
  const { loading } = useLoading()
  return (
    <>
      <Head>
        <title>We Remote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <SearchBar />
      </header>
      {loading ? (
        <>
          <Head>
            <title>Loading...</title>
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <section className={styles.loading}>
            <h1 className={styles.title}>Loading...</h1>
          </section>
        </>
      ) : (
        children
      )}
    </>
  )
}
