import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to my first Search page</h1>
      <h2>
        type on the search bar at the top and click search! (enter works as
        well)
      </h2>
    </>
  )
}

export default Home
