import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { FormEvent, useState } from "react"
import { searchInApi, clearInput } from "services/search"

const Home: NextPage = () => {
  const [input, setInput] = useState<string>("")
  const handleSubmit = (event: FormEvent) => {
    event.preventDefault()
    searchInApi(input).then(console.log)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={handleSubmit}>
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
        />
        <Link href={`/search/${clearInput(input)}`}>
          <a>
            <button type="submit">search</button>
          </a>
        </Link>
      </form>
    </>
  )
}

export default Home
